### ISSUE TITLE
Create Expenses API functionality

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/expense-front#10]
To do when #6 and #4  are resolved.
Create following methods in ApiService to retrieve data from backend:
- _getAllExpenses_() for "/expenses" method **GET**
- _getExpenseById_() for "/expense/{id}" method **GET**
- _saveExpense_() for "/expense" method **POST**
- _updateExpense_() for "/expense/{id}" method **PUT**
- _deleteExpense_() for "/expense/{id}" method **DELETE**

The corresponding methods to handle the response should be implemented in expense.ts.

Test the functionality by using console.log or Network in page inspection to see that the response from backend is received.
Make the method to retrieve all categories to be called when the application starts.

**Comment by mineo71** [comment]
<img width="1325" alt="Screenshot 2020-02-28 at 20 36 05" src="https://user-images.githubusercontent.com/23060147/75577119-f6637300-5a69-11ea-9cb2-d1846881f688.png">
what is it?

**Comment by mineo71** [comment]
@kovalshmidt i cant find answers

**Comment by mineo71** [comment]
it dont do the import , also i dont know why there is void near ngOnInit

**Comment by mineo71** [comment]
save method , u mean  create

**Comment by mineo71** [comment]
<img width="1325" alt="Screenshot 2020-02-28 at 20 36 05" src="https://user-images.githubusercontent.com/23060147/75580099-d0d96800-5a6f-11ea-8a22-96abc4838115.png">
and this problem

**Comment by mineo71** [comment]
<img width="1214" alt="Screenshot 2020-02-28 at 21 20 08" src="https://user-images.githubusercontent.com/23060147/75580263-1e55d500-5a70-11ea-8302-65fe8a289d58.png">and this problem

**Comment by mineo71** [comment]
<img width="980" alt="Screenshot 2020-02-28 at 21 43 44" src="https://user-images.githubusercontent.com/23060147/75582082-77733800-5a73-11ea-9a41-7043da361104.png">
what i should write here?

**Comment by mineo71** [comment]
save method is like create method ?

**Comment by mineo71** [comment]
![](https://files.slack.com/files-pri/TLAQ69JLW-FUNQN14FJ/screenshot_2020-02-28_at_22.26.42.png)

**Comment by mineo71** [comment]
<img width="783" alt="Screenshot 2020-02-28 at 22 26 42" src="https://user-images.githubusercontent.com/23060147/75584944-9ffe3080-5a79-11ea-90eb-8da4bca04b9e.png">

**Comment by kovalshmidt** [comment]
> <img alt="Screenshot 2020-02-28 at 20 36 05" width="1325" src="https://user-images.githubusercontent.com/23060147/75577119-f6637300-5a69-11ea-9cb2-d1846881f688.png">
> 
> what is it?

you wrote the variable as Object name, variables should start from lower case
<img width="471" alt="Screenshot 2020-02-29 at 11 04 52" src="https://user-images.githubusercontent.com/28290808/75604637-6feb7780-5ae3-11ea-9cd2-66d71b0eaa8f.png">

**Comment by kovalshmidt** [comment]
> <img alt="Screenshot 2020-02-28 at 21 20 08" width="1214" src="https://user-images.githubusercontent.com/23060147/75580263-1e55d500-5a70-11ea-8302-65fe8a289d58.png">and this problem

Here you say: variable with name 'expense' is of type Expense and is equal to an empty array.
you should say: variable with name 'expenses' is an array of Expense and is equal to an empty array.

**Comment by kovalshmidt** [comment]
> <img alt="Screenshot 2020-02-28 at 21 43 44" width="980" src="https://user-images.githubusercontent.com/23060147/75582082-77733800-5a73-11ea-9a41-7043da361104.png">
> 
> what i should write here?

If you have an array of expenses, and you delete one of them, you have to update that array and remove from there the deleted expense.
