### ISSUE TITLE
Create ApiService

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/expense-front#4]
Add urls for Category and Expense requests

**Comment by kovalshmidt** [comment]
@Vitalik3310 you just need to create the ApiService as service and add urls for all the possible cases with Category and Expense (check backend) and check note_it to see how it is done. You don't have to write methods, that is something that is assigned in other issues.

**Comment by kovalshmidt** [comment]
You have to do something like that, but for our expense application and for expense API of Category and Expense. Pull the expense-back project to see the updated APIs.

![image](https://user-images.githubusercontent.com/28290808/75144675-19a3c080-5700-11ea-9efb-12c293b8bb6e.png)

**Comment by mineo71** [comment]
i am pinging u 
Do it !!! @Vitalik3310 
i am ready to do my issues
