### ISSUE TITLE
Can't delete category

### ISSUE THREAD

**Issue by mineo71** [kovalshmidt/expense-front#70]
Can't delete categories, in this example I can't delete library category but sometimes you can't delete other categories.
<img width="1680" alt="Screenshot 2020-03-22 at 11 25 04" src="https://user-images.githubusercontent.com/23060147/77246468-3c0df880-6c30-11ea-90d6-a8773444a99a.png">

**Comment by kovalshmidt** [comment]
Issue resolved on backend. Issue number 16.
