### ISSUE TITLE
Add Routing

### ISSUE THREAD

**Issue by kovalshmidt** [kovalshmidt/expense-front#9]
Before taking this issue, issues  #8 and #5 should be resolved.

follow the example in this video:
https://www.youtube.com/watch?v=YscGmaaEplo&list=PLVApX3evDwJ2keNFsQ4PhA1yVaXpto2oN&index=10

The app should work in a way that clicking Expenses on Navbar we should have a page where on top there is Navbar and below the Expense component with the message "expense works!".
 Clicking on Home should return to the main page that has href="/" and show "home works!". The same should work with Categories.

**Comment by kovalshmidt** [comment]
@mineo71 there are some issues in the code. Please be more careful before pushing.
<img width="652" alt="Screenshot 2020-02-23 at 19 37 55" src="https://user-images.githubusercontent.com/28290808/75116745-2b3f8680-5674-11ea-9b5d-3e83ef99421f.png">

**Comment by mineo71** [comment]
what was the problem  ^

**Comment by mineo71** [comment]
I saw @kovalshmidt  why the problem appears, is it because of the (") and without margins

**Comment by mineo71** [comment]
<img width="586" alt="Screenshot 2020-02-23 at 20 31 38" src="https://user-images.githubusercontent.com/23060147/75117590-832dbb80-567b-11ea-8530-45ca0e7823bb.png">
if it  was in bold i would fix it
